"""Regenerate LaTeX tables (T1..T3) from results/ledger.jsonl. [Phase 4]

T1 main results (primary K, aggregated over seeds), T2 K-ablation, T3 reproducibility appendix.
Reads only the ledger (invariant 6) and writes ``\\input``-able ``.tex`` to ``paper/tables/``, each
with a provenance comment naming the run_ids it consumed. See paper/README.md for the table->claim
map.
"""

from __future__ import annotations

from edc.config import REPO_ROOT
from edc.ledger import read_all

try:  # sibling import when run as a script (analysis/ on sys.path)
    from aggregate import aggregate_by_k, selective_rows, tasks_present
except ImportError:  # pragma: no cover
    from analysis.aggregate import aggregate_by_k, selective_rows, tasks_present

TABLE_DIR = REPO_ROOT / "paper" / "tables"


def _esc(s: str) -> str:
    return str(s).replace("_", r"\_")


def _pm(mean_std: tuple[float, float], nd: int = 3) -> str:
    m, s = mean_std
    return f"${m:.{nd}f} \\pm {s:.{nd}f}$"


def _tabular(header: list[str], rows: list[list[str]], colspec: str, caption: str,
             label: str, provenance: str) -> str:
    lines = [
        f"% auto-generated by analysis/make_tables.py — do not edit. {provenance}",
        r"\begin{table}[t]", r"  \centering", f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        f"  \\begin{{tabular}}{{{colspec}}}", r"    \toprule",
        "    " + " & ".join(header) + r" \\", r"    \midrule",
    ]
    lines += ["    " + " & ".join(r) + r" \\" for r in rows]
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def _t1(rows: list[dict]) -> str:
    """Main results, one row per task (each at its own primary K, aggregated over seeds)."""
    body, all_ids = [], []
    for task in tasks_present(rows):
        agg = aggregate_by_k(rows, task=task)
        a = agg[max(agg)]                                  # primary K = largest for that task
        win = f"{a['seeds_ci_excludes_0']}/{a['n_seeds']}"
        body.append([
            _esc(task), str(a["k_restarts"]), _pm(a["accuracy_id"], 2), _pm(a["aurc_geometry"]),
            _pm(a["aurc_best_energy"]), _pm(a["delta_aurc"]), win, _pm(a["ltt_coverage"], 2),
        ])
        all_ids += a["run_ids"]
    header = ["task", "$K$", "acc", "AURC geom", "AURC energy", r"$\Delta$AURC", "seeds win",
              "LTT cov"]
    return _tabular(
        header, body, "lrcccccc",
        "Main selective-prediction results across reasoning families: geometry vs the best "
        "raw-energy baseline (mean$\\pm$std over seeds). $\\Delta$AURC $>0$ with the CI clearing 0 "
        "means geometry wins.",
        "tab:main", f"run_ids={all_ids}")


def _t2(agg: dict[int, dict]) -> str:
    rows = []
    all_ids: list[str] = []
    for k, a in agg.items():
        rows.append([
            str(k), _pm(a["aurc_geometry"]), _pm(a["aurc_best_energy"]), _pm(a["delta_aurc"]),
            f"{a['seeds_ci_excludes_0']}/{a['n_seeds']}", _pm(a["ltt_coverage"], 2),
        ])
        all_ids += a["run_ids"]
    header = ["$K$", "AURC geom", "AURC energy", r"$\Delta$AURC", "seeds win", "LTT cov"]
    return _tabular(
        header, rows, "rccccc",
        "Restart ablation: does landscape geometry across $K$ restarts add signal over a single "
        "descent ($K{=}1\\approx$ EBT)? Lift is $\\Delta$AURC $>0$ with the CI clearing 0.",
        "tab:kablation", f"run_ids={all_ids}")


def _t3(rows: list[dict]) -> str:
    sel = selective_rows(rows)
    env = sel[-1]["env"] if sel else {}
    body = [
        [_esc(r["run_id"]), str(r["seed"]),
         str(r["metrics"].get("k_restarts", "?")), _esc(r["config_hash"]), _esc(r["git_sha"])]
        for r in sorted(sel, key=lambda r: (r["metrics"].get("k_restarts", 0), r["seed"]))
    ]
    caption = (f"Reproducibility appendix. Env: python {env.get('python', '?')}, "
               f"jax {env.get('jax', '?')} ({env.get('jax_backend', '?')}). "
               f"Every row regenerates from seed + config via \\texttt{{run\\_sweep}}.")
    return _tabular(["run\\_id", "seed", "$K$", "config hash", "git sha"], body, "lrrll",
                    caption, "tab:repro", f"n_rows={len(body)}")


def main() -> int:
    rows = read_all()
    tasks = tasks_present(rows)
    print(f"[tables] {len(rows)} ledger rows; tasks = {tasks}")
    if not tasks:
        print("[tables] no split='selective' rows — run experiments/run_sweep.py first.")
        return 0
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    # T2 (K-ablation) uses whichever task has a K-sweep (>1 distinct K); default the first.
    kablation_task = next((t for t in tasks if len(aggregate_by_k(rows, task=t)) > 1), tasks[0])
    outputs = {
        "T1_main.tex": _t1(rows),
        "T2_kablation.tex": _t2(aggregate_by_k(rows, task=kablation_task)),
        "T3_repro.tex": _t3(rows),
    }
    for name, tex in outputs.items():
        (TABLE_DIR / name).write_text(tex)
        print(f"[tables] wrote {TABLE_DIR / name}")
    print(f"[tables] {len(outputs)} tables -> {TABLE_DIR}  (K-ablation task={kablation_task})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
