"""Regenerate LaTeX tables (T1..T3) from results/ledger.jsonl. [Phase 4]

T1 main results (primary K, aggregated over seeds), T2 K-ablation, T3 reproducibility appendix.
Reads only the ledger (invariant 6) and writes ``\\input``-able ``.tex`` to ``paper/tables/``, each
with a provenance comment naming the run_ids it consumed. See paper/README.md for the table->claim
map.
"""

from __future__ import annotations

from edc.config import REPO_ROOT
from edc.ledger import read_all

try:  # sibling import when run as a script (analysis/ on sys.path)
    from aggregate import (
        aggregate_by_k,
        headline_cell,
        objective_of,
        selective_rows,
        tasks_present,
    )
except ImportError:  # pragma: no cover
    from analysis.aggregate import (
        aggregate_by_k,
        headline_cell,
        objective_of,
        selective_rows,
        tasks_present,
    )

TABLE_DIR = REPO_ROOT / "paper" / "tables"


def _esc(s: str) -> str:
    return str(s).replace("_", r"\_")


def _pm(mean_std: tuple[float, float], nd: int = 3) -> str:
    m, s = mean_std
    return f"${m:.{nd}f} \\pm {s:.{nd}f}$"


def _tabular(header: list[str], rows: list[list[str]], colspec: str, caption: str,
             label: str, provenance: str) -> str:
    lines = [
        f"% auto-generated by analysis/make_tables.py — do not edit. {provenance}",
        r"\begin{table}[t]", r"  \centering", f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        # shrink-to-fit only when the table is wider than the text column (never enlarges).
        r"  \resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{%",
        f"  \\begin{{tabular}}{{{colspec}}}", r"    \toprule",
        "    " + " & ".join(header) + r" \\", r"    \midrule",
    ]
    lines += ["    " + " & ".join(r) + r" \\" for r in rows]
    lines += [r"    \bottomrule", r"  \end{tabular}}", r"\end{table}", ""]
    return "\n".join(lines)


def _t1(rows: list[dict]) -> str:
    """Main results, one row per task (each at its own primary K, aggregated over seeds).

    Reports geometry's ΔAURC against **both** the best raw-energy baseline (invariant-8 sacred test)
    and the best of *all* baselines (energy + MSP + temperature + entropy), with the seeds-win count
    for the stronger, all-baseline comparison.
    """
    body, all_ids = [], []
    for task in tasks_present(rows):
        a = headline_cell(rows, task=task)             # largest same-config baseline-carrying sweep
        win = f"{a['seeds_ci_excludes_0_baseline']}/{a['n_seeds']}"
        body.append([
            _esc(task), str(a["k_restarts"]), _pm(a["accuracy_id"], 2), _pm(a["aurc_geometry"]),
            _pm(a["delta_aurc"]), _pm(a["delta_aurc_baseline"]), win, _pm(a["ltt_coverage"], 2),
        ])
        all_ids += a["run_ids"]
    header = ["task", "$K$", "acc", "AURC geom", r"$\Delta$AURC vs energy",
              r"$\Delta$AURC vs best base", "seeds win", "LTT cov"]
    return _tabular(
        header, body, "lrcccccc",
        "Main selective-prediction results across reasoning families (mean$\\pm$std over seeds): "
        "geometry's $\\Delta$AURC over the best raw-energy baseline and over the best of all "
        "baselines (energy, MSP, temperature-scaled MSP, predictive entropy). $\\Delta$AURC $>0$ "
        "with the CI clearing 0 means geometry wins; ``seeds win`` counts seeds beating the best "
        "overall baseline.",
        "tab:main", f"run_ids={all_ids}")


def _t2(agg: dict[int, dict]) -> str:
    rows = []
    all_ids: list[str] = []
    for k, a in agg.items():
        rows.append([
            str(k), _pm(a["aurc_geometry"]), _pm(a["aurc_best_energy"]), _pm(a["delta_aurc"]),
            f"{a['seeds_ci_excludes_0']}/{a['n_seeds']}", _pm(a["ltt_coverage"], 2),
        ])
        all_ids += a["run_ids"]
    header = ["$K$", "AURC geom", "AURC energy", r"$\Delta$AURC", "seeds win", "LTT cov"]
    return _tabular(
        header, rows, "rccccc",
        "Restart ablation: does landscape geometry across $K$ restarts add signal over a single "
        "descent ($K{=}1\\approx$ EBT)? Lift is $\\Delta$AURC $>0$ with the CI clearing 0.",
        "tab:kablation", f"run_ids={all_ids}")


def _t2b(rows: list[dict]) -> str:
    """Feature-group leave-one-out ablation (A1): AURC per subset, one column per task.

    ``full`` is the whole geometry vector; ``drop_energy`` is geometry *without* energy columns —
    if it stays near ``full`` (and below raw energy), the basin/curvature/dynamics features are
    genuinely carrying the win, not merely re-using energy.
    """
    tasks = tasks_present(rows)
    cells = {t: headline_cell(rows, task=t).get("feature_ablation", {}) for t in tasks}
    variants = ["full", "drop_basin", "drop_energy", "drop_curv", "drop_dynamics"]
    body = []
    for v in variants:
        row = [_esc(v)]
        for t in tasks:
            fa = cells[t].get(v)
            row.append(_pm(fa) if fa else "--")
        body.append(row)
    header = ["subset (AURC, lower=better)", *[_esc(t) for t in tasks]]
    colspec = "l" + "c" * len(tasks)
    return _tabular(
        header, body, colspec,
        "Feature-group leave-one-out ablation: test AURC of the geometry mapper refit on subsets "
        "of the 14 features (mean$\\pm$std over seeds). ``drop\\_X`` removes that group; comparing "
        "``drop\\_energy`` to ``full`` isolates the non-energy geometry contribution.",
        "tab:ablation", "feature-group leave-one-out")


def _t4(rows: list[dict]) -> str:
    """Complementarity (A1c): does geometry add *conditional* signal over a learned softmax?

    One row per (task, reasoner). ``vs softmax`` is head-to-head (geometry-alone minus the best
    softmax baseline); ``geom adds`` is a mapper on [softmax] minus a mapper on [geometry+softmax] —
    positive means geometry is complementary even where it ties head-to-head.
    """
    body, all_ids = [], []
    for task in tasks_present(rows):
        for o in sorted({objective_of(r) for r in selective_rows(rows, task=task)}):
            a = headline_cell(rows, task=task, objective=o)
            if not a.get("has_geom_adds"):
                continue
            body.append([
                _esc(task), _esc(o), _pm(a["delta_aurc_baseline"]), _pm(a["delta_aurc_geom_adds"]),
                f"{a['seeds_ci_excludes_0_geom_adds']}/{a['n_seeds']}",
            ])
            all_ids += a["run_ids"]
    header = ["task", "reasoner", r"$\Delta$AURC vs softmax", r"$\Delta$AURC geom \emph{adds}",
              "seeds add"]
    return _tabular(
        header, body, "llccc",
        "Complementarity (mean$\\pm$std over seeds): head-to-head geometry vs the best softmax "
        "baseline, and whether geometry \\emph{adds} conditional signal on top of a learned "
        "softmax (a mapper on [geometry $\\cup$ softmax] vs [softmax]). $>0$ with the CI clearing "
        "0 (``seeds add'') means geometry is complementary, even where it ties head-to-head.",
        "tab:complementarity", f"run_ids={all_ids}")


def _t3(rows: list[dict]) -> str:
    sel = selective_rows(rows)
    env = sel[-1]["env"] if sel else {}
    body = [
        [_esc(r["run_id"]), str(r["seed"]),
         str(r["metrics"].get("k_restarts", "?")), _esc(r["config_hash"]), _esc(r["git_sha"])]
        for r in sorted(sel, key=lambda r: (r["metrics"].get("k_restarts", 0), r["seed"]))
    ]
    caption = (f"Reproducibility appendix. Env: python {env.get('python', '?')}, "
               f"jax {env.get('jax', '?')} ({env.get('jax_backend', '?')}). "
               f"Every row regenerates from seed + config via \\texttt{{run\\_sweep}}.")
    return _tabular(["run\\_id", "seed", "$K$", "config hash", "git sha"], body, "lrrll",
                    caption, "tab:repro", f"n_rows={len(body)}")


def main() -> int:
    rows = read_all()
    tasks = tasks_present(rows)
    print(f"[tables] {len(rows)} ledger rows; tasks = {tasks}")
    if not tasks:
        print("[tables] no split='selective' rows — run experiments/run_sweep.py first.")
        return 0
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    # T2 (K-ablation) uses whichever task has a K-sweep (>1 distinct K); default the first.
    kablation_task = next((t for t in tasks if len(aggregate_by_k(rows, task=t)) > 1), tasks[0])
    outputs = {
        "T1_main.tex": _t1(rows),
        "T2_kablation.tex": _t2(aggregate_by_k(rows, task=kablation_task)),
        "T2b_feature_ablation.tex": _t2b(rows),
        "T3_repro.tex": _t3(rows),
    }
    t4 = _t4(rows)                                  # only when complementarity rows exist
    if r"\midrule" in t4 and t4.split(r"\midrule")[1].split(r"\bottomrule")[0].strip():
        outputs["T4_complementarity.tex"] = t4
    for name, tex in outputs.items():
        (TABLE_DIR / name).write_text(tex)
        print(f"[tables] wrote {TABLE_DIR / name}")
    print(f"[tables] {len(outputs)} tables -> {TABLE_DIR}  (K-ablation task={kablation_task})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
