"""Regenerate LaTeX tables (T1..T3) from results/ledger.jsonl. [Phase 4]

T1 main results (primary K, aggregated over seeds), T2 K-ablation, T3 reproducibility appendix.
Reads only the ledger (invariant 6) and writes ``\\input``-able ``.tex`` to ``paper/tables/``, each
with a provenance comment naming the run_ids it consumed. See paper/README.md for the table->claim
map.
"""

from __future__ import annotations

from edc.config import REPO_ROOT
from edc.ledger import read_all

try:  # sibling import when run as a script (analysis/ on sys.path)
    from aggregate import aggregate_by_k, selective_rows
except ImportError:  # pragma: no cover
    from analysis.aggregate import aggregate_by_k, selective_rows

TABLE_DIR = REPO_ROOT / "paper" / "tables"


def _esc(s: str) -> str:
    return str(s).replace("_", r"\_")


def _pm(mean_std: tuple[float, float], nd: int = 3) -> str:
    m, s = mean_std
    return f"${m:.{nd}f} \\pm {s:.{nd}f}$"


def _tabular(header: list[str], rows: list[list[str]], colspec: str, caption: str,
             label: str, provenance: str) -> str:
    lines = [
        f"% auto-generated by analysis/make_tables.py — do not edit. {provenance}",
        r"\begin{table}[t]", r"  \centering", f"  \\caption{{{caption}}}", f"  \\label{{{label}}}",
        f"  \\begin{{tabular}}{{{colspec}}}", r"    \toprule",
        "    " + " & ".join(header) + r" \\", r"    \midrule",
    ]
    lines += ["    " + " & ".join(r) + r" \\" for r in rows]
    lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def _t1(agg: dict[int, dict], primary_k: int) -> str:
    a = agg[primary_k]
    verdict = ("geometry beats energy" if a["geometry_wins_all"]
               else f"{a['seeds_ci_excludes_0']}/{a['n_seeds']} seeds separate")
    rows = [
        ["ID accuracy", _pm(a["accuracy_id"])],
        ["AURC geometry (lower better)", _pm(a["aurc_geometry"])],
        [f"AURC best energy ({_esc('/'.join(a['best_energy_names']))})",
         _pm(a["aurc_best_energy"])],
        [r"$\Delta$AURC (energy $-$ geometry)", _pm(a["delta_aurc"])],
        ["seeds with 95\\% CI excluding 0", f"{a['seeds_ci_excludes_0']} / {a['n_seeds']}"],
        ["LTT coverage", _pm(a["ltt_coverage"])],
        ["LTT abstention rate", _pm(a["ltt_abstain_rate"])],
        ["LTT selective risk ($\\alpha=0.1$)", _pm(a["ltt_selective_risk"])],
    ]
    return _tabular(
        ["metric", "value"], rows, "lr",
        f"Main selective-prediction results on arithmetic ($K={primary_k}$, "
        f"{a['n_seeds']} seeds): {verdict}.",
        "tab:main", f"run_ids={a['run_ids']}")


def _t2(agg: dict[int, dict]) -> str:
    rows = []
    all_ids: list[str] = []
    for k, a in agg.items():
        rows.append([
            str(k), _pm(a["aurc_geometry"]), _pm(a["aurc_best_energy"]), _pm(a["delta_aurc"]),
            f"{a['seeds_ci_excludes_0']}/{a['n_seeds']}", _pm(a["ltt_coverage"], 2),
        ])
        all_ids += a["run_ids"]
    header = ["$K$", "AURC geom", "AURC energy", r"$\Delta$AURC", "seeds win", "LTT cov"]
    return _tabular(
        header, rows, "rccccc",
        "Restart ablation: does landscape geometry across $K$ restarts add signal over a single "
        "descent ($K{=}1\\approx$ EBT)? Lift is $\\Delta$AURC $>0$ with the CI clearing 0.",
        "tab:kablation", f"run_ids={all_ids}")


def _t3(rows: list[dict]) -> str:
    sel = selective_rows(rows)
    env = sel[-1]["env"] if sel else {}
    body = [
        [_esc(r["run_id"]), str(r["seed"]),
         str(r["metrics"].get("k_restarts", "?")), _esc(r["config_hash"]), _esc(r["git_sha"])]
        for r in sorted(sel, key=lambda r: (r["metrics"].get("k_restarts", 0), r["seed"]))
    ]
    caption = (f"Reproducibility appendix. Env: python {env.get('python', '?')}, "
               f"jax {env.get('jax', '?')} ({env.get('jax_backend', '?')}). "
               f"Every row regenerates from seed + config via \\texttt{{run\\_sweep}}.")
    return _tabular(["run\\_id", "seed", "$K$", "config hash", "git sha"], body, "lrrll",
                    caption, "tab:repro", f"n_rows={len(body)}")


def main() -> int:
    rows = read_all()
    agg = aggregate_by_k(rows)
    print(f"[tables] {len(rows)} ledger rows; K values = {sorted(agg)}")
    if not agg:
        print("[tables] no split='selective' rows — run experiments/run_sweep.py first.")
        return 0
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    primary_k = max(agg)  # headline result uses the largest K (most restart geometry)
    outputs = {
        "T1_main.tex": _t1(agg, primary_k),
        "T2_kablation.tex": _t2(agg),
        "T3_repro.tex": _t3(rows),
    }
    for name, tex in outputs.items():
        (TABLE_DIR / name).write_text(tex)
        print(f"[tables] wrote {TABLE_DIR / name}")
    print(f"[tables] {len(outputs)} tables -> {TABLE_DIR}  (primary K={primary_k})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
